--MONTHLY Sales revenue and growth
-- Step 1: Create a base dataset of delivered orders only
WITH sales AS (
    SELECT 
        fs.order_id,
        fs.product_id,
        fs.price,
        o.order_purchase_timestamp
    FROM FactSales AS fs
    INNER JOIN DimOrders AS o
        ON fs.order_id = o.order_id  -- Join sales with order details
    WHERE o.order_status = 'delivered' -- Filter to only completed (delivered) orders
),
-- Step 2: Aggregate data at a monthly level
monthly_sales AS (
    SELECT 
        DATE_TRUNC('month', order_purchase_timestamp::timestamp) AS month,
        SUM(price) AS monthly_revenue,
        COUNT(DISTINCT order_id) AS monthly_orders,
        SUM(price) / COUNT(DISTINCT order_id) AS average_order_value
    FROM sales
    GROUP BY DATE_TRUNC('month', order_purchase_timestamp::timestamp)
)
-- Step 3: Calculate month-over-month growth
SELECT 
    month,
    monthly_revenue,
    monthly_orders,
    average_order_value,
    -- Previous month's revenue using window function
    LAG(monthly_revenue) OVER (ORDER BY month) AS previous_month_revenue, 
    -- Month-over-month growth percentage
    (
        (monthly_revenue - LAG(monthly_revenue) OVER (ORDER BY month)) -- Change in revenue
        / NULLIF(LAG(monthly_revenue) OVER (ORDER BY month), 0) -- Avoid division by zero
    ) * 100 AS monthly_growth_pct
FROM monthly_sales
ORDER BY month; -- Ensure results are in chronological order

--Sales performanc by product categories
-- Step 1: Join sales, orders, and product tables
select
	p.product_category_name,
	-- Total revenue generated per category
	SUM(fs.price) as total_revenue, 
	-- Total number of unique orders per category
	COUNT(distinct fs.order_id) as total_orders,
	 -- Average order value (AOV) per category
	ROUND((SUM(fs.price) / COUNT(DISTINCT fs.order_id))::numeric, 2) AS average_order_value,
	-- Rank categories by total revenue (highest first)
	RANK() OVER (ORDER BY SUM(fs.price) DESC) AS revenue_rank
from factsales as fs
-- Join with orders to filter only delivered transactions
inner join dimorders as o
 on fs.order_id = o.order_id
-- Join with product table to get category information 
inner join dimproduct as p 
on fs.product_id = p.product_id
-- Step 2: Filter to only completed (delivered) orders
where order_status = 'delivered'
-- Step 3: Aggregate results by product category
group by p.product_category_name
-- Step 4: Sort categories by highest revenue
order by total_revenue desc
-- Step 5: Return only top 10 categories
limit 10;
--
---- Which sellers generate the most revenue?
-- Step 1: Join sales, orders, and seller tables
select
	s.seller_id,
	-- Total revenue generated by each seller
	SUM(fs.price) as total_revenue,
	-- Total number of unique orders handled by each seller
	COUNT(DISTINCT fs.order_id) as total_orders,
	-- Average order value (AOV) per seller
	ROUND((SUM(fs.price) / COUNT(DISTINCT fs.order_id))::numeric, 2) AS average_order_value,
	-- Rank sellers based on total revenue (highest first)
	RANK() OVER (ORDER BY SUM(fs.price) DESC) AS revenue_rank
from factsales as fs
-- Join with orders to filter only delivered transactions
inner join dimorders as o
 on fs.order_id = o.order_id
 -- Join with seller table to get seller information
inner join dimseller as s
on fs.seller_id = s.seller_id 
-- Step 2: Filter to only completed (delivered) orders
where order_status = 'delivered'
-- Step 3: Aggregate results by seller
group by s.seller_id 
-- Step 4: Sort sellers by highest revenue
order by total_revenue desc
-- Step 5: Return only top 10 sellers
limit 10;
----Which sellers generate the most revenue
select
	 c.customer_state,
	SUM(fs.price) as total_revenue,
	COUNT(DISTINCT fs.order_id) as total_orders,
	ROUND((SUM(fs.price) / COUNT(DISTINCT fs.order_id))::numeric, 2) AS average_order_value,
	RANK() OVER (ORDER BY SUM(fs.price) DESC) AS revenue_rank
from factsales as fs
inner join dimorders as o
 on fs.order_id = o.order_id
inner join dimcustomer as c
on o.customer_id = c.customer_id 
where order_status = 'delivered'
group by c.customer_state
order by total_revenue desc
limit 10;

-- sales revenue by payment method

WITH order_revenue AS (
    SELECT
        fs.order_id,
        SUM(fs.price) AS order_revenue
    FROM FactSales AS fs
    INNER JOIN DimOrders AS o
        ON fs.order_id = o.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY fs.order_id
)
SELECT
    op.payment_type,
    SUM(orv.order_revenue) AS total_revenue,
    COUNT(DISTINCT orv.order_id) AS total_orders,
    ROUND((SUM(orv.order_revenue) / COUNT(DISTINCT orv.order_id))::numeric, 2) AS average_order_value,
    RANK() OVER (ORDER BY SUM(orv.order_revenue) DESC) AS revenue_rank
FROM order_revenue AS orv
INNER JOIN DimOrderPayments AS op
    ON orv.order_id = op.order_id
GROUP BY op.payment_type
ORDER BY total_revenue DESC;
